# Generated by Django 3.2.9 on 2021-12-04 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jalan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jalan', models.CharField(max_length=60, null=True)),
                ('tipe_jalan', models.CharField(choices=[('V', 'Kelas V'), ('IV', 'Kelas IV'), ('III', 'Kelas III'), ('II', 'Kelas II'), ('I', 'Kelas I')], max_length=10)),
                ('kondisi_trotoar', models.CharField(choices=[('0', 'Skala 0'), ('1', 'Skala 1'), ('2', 'Skala 2'), ('3', 'Skala 3')], max_length=10)),
                ('kondisi_penerangan', models.CharField(choices=[('1', 'Skala 1'), ('2', 'Skala 2'), ('3', 'Skala 3')], max_length=10)),
                ('kondisi_jalan', models.CharField(choices=[('1', 'Skala 1'), ('2', 'Skala 2'), ('3', 'Skala 3'), ('4', 'Skala 4'), ('5', 'Skala 5')], max_length=10)),
                ('jalan_sekitar', models.ManyToManyField(blank=True, related_name='_sekja_jalan_jalan_sekitar_+', to='sekja.Jalan')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Pengguna', 'Pengguna')], default='Admin', max_length=8),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_laporan', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('W', 'Waiting List'), ('P', 'On Progress'), ('S', 'Selesai')], max_length=15)),
                ('pesan', models.CharField(max_length=256)),
                ('jalan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dilaporkan_dalam', to='sekja.jalan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membuat_laporan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('komentar', models.CharField(max_length=256)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='berkomentar', to=settings.AUTH_USER_MODEL)),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to='sekja.laporan')),
            ],
        ),
    ]
