# Generated by Django 3.2.9 on 2021-12-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekja', '0002_auto_20211204_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Pengguna')], default=2),
        ),
    ]
