# Generated by Django 3.2.9 on 2021-12-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekja', '0004_alter_user_no_kk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='no_KK',
            field=models.IntegerField(unique=True),
        ),
    ]
