# Generated by Django 3.2.9 on 2021-12-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekja', '0006_alter_user_no_kk'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='judul',
            field=models.CharField(default='Tanpa Judul', max_length=32),
        ),
    ]
