# Generated by Django 3.2.9 on 2021-12-08 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekja', '0007_laporan_judul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='status',
            field=models.CharField(choices=[('W', 'Waiting List'), ('P', 'On Progress'), ('S', 'Selesai')], default='W', max_length=15),
        ),
    ]
